apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logging.fullname" . }}-cluster-info
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.awsConfig }}
  {{ $key }}: {{ quote $val }}
  {{- end }}