apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logging.fullname" . }}-config
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: |
    {{- (tpl $val $) | nindent 4 }}
  {{- end }}
