apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "backend.fullname" . }}-swagger
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      {{ toYaml .Values.swagger.ingress.hosts | indent 4 }}
  - port:
      number: 9443
      name: http-dev
      protocol: HTTP
    hosts:
      {{ toYaml .Values.swagger.ingress.hosts | indent 4 }}