apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "backend.fullname" . }}-swagger
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- include "swagger.ingress.hosts" . | nindent 4 }}