{{- if .Values.ingress.enabled -}}  
  {{- $pathType := .Values.swagger.ingress.pathType | default "Prefix" -}}
  {{- $serviceName := printf "%s" (include "backend.fullname" .) -}}
  {{- $servicePort := .Values.swagger.ingress.servicePort | default 80 -}}
  {{- $paths := .Values.ingress.paths | default "/" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ template "backend.namespace" . }}
  name: {{ include "backend.fullname" . }}-swagger-ingress
  # name: swagger-ui
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range $host := .Values.ingress.hosts }}
      - host: {{ tpl $host $ }}
        http:
          paths:
    {{- range $p := $paths }}
            - path: {{ tpl $p $ }}
              pathType: {{ $pathType }}
              backend:
                service:
                  name: {{ $serviceName }}
                  port:
                    number: {{ $servicePort }}
      {{- end }}
      {{- end -}}
    {{- end }}
  tls:
{{ tpl (toYaml .Values.ingress.tls | indent 4) . }}
{{- end -}}