apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  labels:
    kind: swagger-ui
  annotations:
    {{- include "backend.serviceAnnotations" . | nindent 4 }}
spec:
  selector:
    tier: swagger-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: {{ .Values.service.type }}