vender: "AWS" # AWS | on-premise

environment: "develop"

ingress:
  enabled: false

istio-gateway:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "library"
      effect: "NoSchedule"

istiod:
  global:
    proxy:
      autoInject: disabled
  pilot:
    tolerations:
      - key: kind
        operator: "Equal"
        value: "library"
        effect: "NoSchedule"

preInstall:
  tolerations:
      - key: kind
        operator: "Equal"
        value: "library"
        effect: "NoSchedule"