ingress:
  enabled: false

istio-gateway:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "api"
      effect: "NoSchedule"

istiod:
  pilot:
    tolerations:
      - key: kind
        operator: "Equal"
        value: "api"
        effect: "NoSchedule"
