apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "external-dns.fullname" . }}-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "external-dns.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "external-dns.fullname" . }}
  namespace: kube-system