apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-so1s-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: so1s-project-prod

  source:
    repoURL: https://github.com/so1s/so1s-deploy.git
    targetRevision: release/v1.2.0
    path: apps/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
