apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "kube-prometheus-stack.fullname" . }}-grafana
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      {{ toYaml .Values.grafana.ingress.hosts | indent 4 }}