replicaCount: 1

image:
  repository: "ghcr.io/so1s/frontend"
  tag: "latest"

imagePullSecrets: []

imagePullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    memory: "350Mi"
  requests:
    memory: "150Mi"

podAnnotations:
  sidecar.istio.io/inject: "true"

autoscaling:
  enabled: false

ingress:
  hosts:
    - test-www.so1s.io

tolerations:
  - key: kind
    operator: "Equal"
    value: "application"
    effect: "NoSchedule"

preInstall:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "application"
      effect: "NoSchedule"

config:
  nginxConf: |
    server {
      include /etc/nginx/mime.types;
      client_max_body_size 0;
      listen 80;

      location ~ /api {
        resolver kube-dns.kube-system.svc.cluster.local;
        set $target "http://so1s-dev.backend.svc.cluster.local:80";

        proxy_pass $target;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
      }

      location ~ /swagger-ui {
        resolver kube-dns.kube-system.svc.cluster.local;
        set $target "http://so1s-dev.backend.svc.cluster.local:80";

        proxy_pass $target;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
      }

      location ~ /swagger-resources {
        resolver kube-dns.kube-system.svc.cluster.local;
        set $target "http://so1s-dev.backend.svc.cluster.local:80";

        proxy_pass $target;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
      }

      location ~ /v3/api-docs {
        resolver kube-dns.kube-system.svc.cluster.local;
        set $target "http://so1s-dev.backend.svc.cluster.local:80";

        proxy_pass $target;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
      }

      location ~ /webjars {
        resolver kube-dns.kube-system.svc.cluster.local;
        set $target "http://so1s-dev.backend.svc.cluster.local:80";

        proxy_pass $target;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
      }

      location ~ /dashboard/ {
        resolver kube-dns.kube-system.svc.cluster.local;
        set $target "http://monitoring-grafana.monitoring.svc.cluster.local:80";

        proxy_pass $target;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
      }

      location ~ /kiali/ {
        resolver kube-dns.kube-system.svc.cluster.local;
        set $target "http://kiali.logging.svc.cluster.local:20001";

        proxy_pass $target;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
      }

      location ~ /kibana/ {
        resolver kube-dns.kube-system.svc.cluster.local;
        set $target "http://logging-kibana.logging.svc.cluster.local:5601";

        proxy_pass $target;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
      }

      location ~ /healthz {
        return 200;
      }
      
      location ~ / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        try_files $uri /index.html;
      }

      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
        root   /usr/share/nginx/html;
      }

    }
