replicaCount: 1

image:
  repository: "ghcr.io/so1s/frontend"
  tag: "latest"

imagePullSecrets:
  - name: so1s

imagePullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    memory: "350Mi"
  requests:
    memory: "150Mi"

podAnnotations:
  sidecar.istio.io/inject: "true"

autoscaling:
  enabled: false

ingress:
  hosts:
    - test-www.so1s.io

tolerations:
  - key: kind
    operator: "Equal"
    value: "application"
    effect: "NoSchedule"

preInstall:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "application"
      effect: "NoSchedule"

config:
  nginxConf: |
    server {
      include /etc/nginx/mime.types;
      client_max_body_size 0;
      listen 80;
      
      # https://serverfault.com/a/593003
      set $backend "so1s-dev.backend.svc.cluster.local:80";

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        try_files $uri /index.html;
      }

      location /api/v1 {
        proxy_pass http://$backend/api/v1;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header Host $host;
        proxy_http_version 1.1;
      }

      location /healthz {
        return 200;
      }

      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
        root   /usr/share/nginx/html;
      }

    }
