replicaCount: 1

image:
  repository: "ghcr.io/so1s/frontend"
  tag: "latest"

imagePullSecrets: []

imagePullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    memory: "350Mi"
  requests:
    memory: "150Mi"

podAnnotations:
  sidecar.istio.io/inject: "true"

autoscaling:
  enabled: false

ingress:
  hosts:
    - test-www.so1s.io

tolerations:
  - key: kind
    operator: "Equal"
    value: "application"
    effect: "NoSchedule"

preInstall:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "application"
      effect: "NoSchedule"

config:
  nginxConf: |
    server {
      include /etc/nginx/mime.types;
      client_max_body_size 0;
      listen 80;

      resolver kube-dns.kube-system.svc.cluster.local;

      set $backend http://so1s-dev.backend.svc.cluster.local:80;
      set $grafana http://monitoring-grafana.monitoring.svc.cluster.local:80;
      set $kibana http://logging-kibana.logging.svc.cluster.local:5601;
      set $kiali http://kiali.logging.svc.cluster.local:20001;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        try_files $uri /index.html;
      }

      location /api {
        proxy_pass $backend;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
      }

      location /swagger-ui {
        proxy_pass $backend;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
      }

      location /swagger-resources {
        proxy_pass $backend;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
      }

      location /v3/api-docs {
        proxy_pass $backend;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
      }

      location /webjars {
        proxy_pass $backend;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
      }

      location /grafana {
        proxy_pass $grafana;

        proxy_redirect / /grafana/;
        proxy_redirect $grafana/ /grafana/;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
      }

      location /kibana {
        proxy_pass $kibana;

        proxy_redirect / /kibana/;
        proxy_redirect $kibana/ /kibana/;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
      }

      location /kiali {
        proxy_pass $kiali;

        proxy_redirect / /kiali/;
        proxy_redirect $kiali/ /kiali/;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
      }

      location /healthz {
        return 200;
      }

      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
        root   /usr/share/nginx/html;
      }

    }
