replicaCount: 2

image:
  repository: "ghcr.io/so1s/frontend"
  tag: "1.4.0"

imagePullSecrets: []

imagePullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    memory: "350Mi"
  requests:
    memory: "150Mi"

podAnnotations:
  sidecar.istio.io/inject: "true"

autoscaling:
  enabled: false

ingress:
  hosts:
    - www.so1s.io

tolerations:
  - key: kind
    operator: "Equal"
    value: "application"
    effect: "NoSchedule"

podAnnotations: 
  sidecar.istio.io/inject: "true"

config: 
  nginxConf: |
    server {
      include /etc/nginx/mime.types;
      client_max_body_size 0;
      listen 80;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        try_files $uri /index.html;
      }

      location /api {
        proxy_pass http://so1s-prod.backend.svc.cluster.local:80;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
      }

      location /healthz {
        return 200;
      }

      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
        root   /usr/share/nginx/html;
      }

    }