apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-logging-app-prod
  namespace: argocd
  finalizers: []
spec:
  project: so1s-project-prod

  source:
    repoURL: https://github.com/so1s/so1s-deploy.git
    targetRevision: v1.5.0
    path: charts/logging

    helm:
      releaseName: logging
      valueFiles:
        - prod-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
