apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-istio-base-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: so1s-project-prod

  source:
    repoURL: git@github.com:So1S/deploy.git
    targetRevision: main
    path: charts/istio/istio-base

    helm:
      releaseName: istio-base
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true