apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-monitoring-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: so1s-project-prod

  source:
    repoURL: https://github.com/so1s/so1s-deploy.git
    targetRevision: v1.4.0
    path: charts/monitoring

    helm:
      releaseName: monitoring
      valueFiles:
        - prod-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
