apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-sealed-secrets-prod
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: so1s-project-prod

  # Source of the application manifests
  source:
    repoURL: https://github.com/bitnami-labs/sealed-secrets
    path: helm/sealed-secrets  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
    helm:
      values: |
        tolerations:
          - key: kind
            operator: "Equal"
            value: api
            effect: "NoSchedule"

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: sealed-secrets
  

  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true
