apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-sealed-secrets-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: so1s-project-prod

  source:
    repoURL: https://github.com/bitnami-labs/sealed-secrets
    targetRevision: v0.18.1
    path: helm/sealed-secrets
    helm:
      values: |
        tolerations:
          - key: kind
            operator: "Equal"
            value: api
            effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  

  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true
