apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-backend-app-prod
  namespace: argocd
spec:
  project: so1s-project-prod

  source:
    repoURL: https://github.com/so1s/so1s-deploy.git
    targetRevision: v1.3.1
    path: charts/backend

    helm:
      releaseName: backend
      valueFiles:
        - prod-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
