{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-ingress
  namespace: istio-system
 {{- if .Values.ingress.annotations }} 
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  defaultBackend:
    service:
      name: istio
      port:
        number: 80
  rules:
    - http:
        paths:
         - path: /
           pathType: Prefix
           backend:
            service:
              name: istio
              port:
                number: 80
{{ end -}}