tolerations:
  - key: kind
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"

resources:
  limits:
    memory: "200Mi"
    cpu: "100m"
  requests:
    memory: "200Mi"
    cpu: "100m"
