tolerations:
  - key: kind
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"

nodeAffinity:
  required:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kind
            operator: Equal
            value: database

resources:
  limits:
    memory: "200Mi"
    cpu: "100m"
  requests:
    memory: "200Mi"
    cpu: "100m"
