apiVersion: v2
appVersion: "1.16.0"
version: 0.1.0

name: database
description: A Helm chart for So1s database deployment (Postgresql)
type: application
maintainers:
  - name: JihoLee
    email: optional.int@kakao.com
  - name: SungbinIm
    email: dlatqdlatq@naver.com
  - name: ShinilSeop
    email: shinilseop12@gmail.com
sources:
  - https://github.com/So1S/deploy

dependencies: []
