tolerations:
  - key: kind
    operator: "Equal"
    value: "api"
    effect: "NoSchedule"

nodeAffinity:
  required:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kind
            operator: In
            values:
              - api
