tolerations:
  - key: kind
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"

resources:
  limits:
    memory: "300Mi"
    cpu: "300m"
  requests:
    memory: "300Mi"
    cpu: "300m"
