apiVersion: v1
kind: ServiceAccount
metadata:
  name: hyper-sa
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
  namespace: {{ .Release.Namespace }}