environment: "develop"

fullnameOverride: "sungbin-dev" # 중복된 ClusterRole이 생기면 안되므로 각자 이름을 써놓고 작업해주세요

image:
  repository: "dlatqdlatq/poc-api"
  tag: "v2-test"

imagePullSecrets: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1

resourceQuota:
  cpu: "2000m"
  memory: 2Gi

resources:
  limits:
    memory: "1000Mi"
    cpu: "1000m"
  requests:
    memory: "1000Mi"
    cpu: "1000m"