environment: "develop"

image:
  repository: "dlatqdlatq/poc-api"
  tag: "v2-test"

imagePullSecrets: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1

resourceQuota:
  cpu: "4000m"
  memory: 4Gi

resources:
  limits:
    memory: "1000Mi"
    cpu: "1000m"
  requests:
    memory: "1000Mi"
    cpu: "1000m"