apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  {{- with .Values.config.nginxConf }}
  nginx.conf: |
    {{- . | nindent 4 }}
  {{- end }}