apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config.nginxConf }}
  nginx.conf: |
    {{- (tpl $val $) | nindent 4 }}
  {{- end }}