apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  hosts:
    {{ toYaml .Values.ingress.hosts | indent 4 }}
  gateways:
  - {{ include "frontend.fullname" . }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: {{ include "frontend.fullname" . }}