apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kube-prometheus-stack.fullname" . }}-prometheus
spec:
  hosts:
    {{ toYaml .Values.prometheus.ingress.hosts | indent 4 }}
  gateways:
  - {{ include "kube-prometheus-stack.fullname" . }}-prometheus
  http:
  - match:
    - uri:
        prefix: {{ .Values.prometheus.prometheusSpec.routePrefix }}
    route:
    - destination:
        port:
          number: {{ .Values.prometheus.service.port }}
        host: {{ include "kube-prometheus-stack.fullname" . }}-prometheus