apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana
spec:
  hosts:
    {{ toYaml .Values.kibana.gateway.hosts | indent 4 }}
  gateways:
  - kibana
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 5601
        host: elasticsearch-master-headless
