apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.environment }}-role
rules:          
# 개발 진행 후 추후에 추가 예정
  - apiGroups:  
      - ''      
    resources:
      - ''
    verbs:
      - get
      - list
      - watch