apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: so1s
spec:
  encryptedData:
    .dockerconfigjson: AgAewaxo4S5KhXtxNdXnI67nzrfygVmSmGwGqQQ635MySy1UESoKaZ+fetytM6E5P0fk8pphpEHqiJ8GmoKDgVaeK5nldpyezHuY1FiEK8VRd8E22HINThGlgyUjI+wPV3+K8wavFyxbmbKyduyCYi5URiaQOUMmp/bNxKaaddsjfgoB0cDDfsRK268BuHcMMRttFCeGdgNoiokmUwptwWoYOXmNtj2SV4tNN19rA8EYKEC/KoIcNlzyguaN1+C4ax6M/ICAVkdz1Bwb9xfWjDBvIfMWB/0nE7bpfVsi571dutJryYF4Twe+wPwdTdfnD39KV6NkEguBs7980xAnT/ZTjpHCGEDzODI6cZDyHmG2nrOwwUNWjSrDtLkqXUYk5ppqUwtXS9ybKRv30jcNetx3R9HCmrqj5PCZeqImBV4F+yeEVjkVq+tMwWdTZ5dQVlQekDeRsnwBPuRbXtP64TypecQwAo90XwZMV+PivMpkr2BhO5Sn90V++KMHJMPXkK4JhHh69mkeCJKPdZjPQDO1g614Y96HohehowoDPyAVOpYnKB5A/FzrBuEp8a0YwQ8AGctJaVNA9Os1cznqG+d8tRGaA4gbH2eRk3r22Qoz7Qh5a1hmfkEJDM+sYcF/4UeOVYiTZaYEXppFRkLau0aDQt95+TZOOHGNM8ioDMOawlpqyalNbldBPxmZhoIGzNSVvUdWZZBSOeUpuJ6KAwnB9VjZ/1GypI6lOdSnDkR88ZfAca600gYQZirrYrQXd2EzQ/mz5DRr2GgBHxfY+YSAkI5EFX54DTX6SIczT1mODgVEsrKwQijtJ8F0Cr6DZT8NpucTNdX7H9xP88B0Urvb0avnTVqXZ6r1ntjJkjENJMghfK+zHGxKcpD9xm1ysP2lPeoPbMhYQOOxJVgTq6oahLp0piGjSQ+M6JUR1vOJK95EetnDfZNKQ3uX+uBlVIPXOG7LThqB8QwBHsIyen3NRYYSFMtSuiHngdq/9dw0f/FEzWjcTZzOhbi/GrWQDLLCuWCt6eEzigfu14epY/vl2SufEiy8Cj82W3gx6uDn2UpGBNs7R024FtUpOG402DXg
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: so1s
    type: kubernetes.io/dockerconfigjson

