apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: so1s
spec:
  encryptedData:
    .dockerconfigjson: AgAqywF9yvLTVvx+I5EUlJ+G7+88Nj+w7jjrkKmJ1SNCRUDAOeaFIWQvsKIT5RXbU/JYGSAIexDUuQ4JFOjOxiV6DgIeCSBiVhRDXc2PKI4imBsT/oOgrss90/xw8mKiQrNm8cp1Twyk8ulqWlo0vThvHLLNS5qZuNqD1zLSSgq9SxCyFytHTpz8pBiGdXwNnCRPBS/9mjICJAsXbGAwNjuB/VkrHnlx+5YgYbI8ansAH9rS4y7bIbuJJZRZJAibhfBc38rdF2uEK/SQrbb4p6uKBiqG8d/sThueMddS03CXary2o3MuyCVVGRIQWLywBur6uextqkEZkDfefJ5mTW1+x4HxO7fREAx0YUPXFX9a8+vr70wYzNRbv2zB8L26ItLH0LePL6fsN1obLMxYdqnrVrBHt1+iugILtnmVRc+MIKnhGjyfR9T/zVNjFNY+8dGcdtmJcIBDL9wNT27TBOvheGT6WFTrq8oohw14GnPOX8YbkdBof0ZCIv2Kmc9zJUgsMJqP23JfotErBoGm8+QSYyQmF96H4Q0nQNUI8FfUxDv34uyD3CnNxo3JJyd0PCcCRLwJQNY4ApUTGSD5cc+k/C3X6mj4+5hya8KiD/Ae3yBh9FGrphDaOax0lkGHu8Jw+uQSJ/EZNZVuFbpqrgTvn5DlC3irj9i2W3GD9fTdpBj5iiSXXMULXKrcASZcAW/tKbeYjVguy76iFpJAqPYhaaV9zL7MNuiWT5Yr9dOXDYzRHh/U47BLqeEDyKZ+LOh7OpvWuS/ArN7XB0llfNJjY5aNbFDsmhE0tQ/W+vMZshfq9V1T1n15SzXu0wNY3TW7sU4lQm9f5PtL/NdScB1MMlPyDJPcPDtR6x95twQorKbgzn/uxRgsZ0HmHoDovM13EcUsh/6bS50eT0sIcfxpECy3/hd2rgXj9aBSeCIrHO7smHhbPQqFmsr5fnf2eyd5U0e27yNDYu5C
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: so1s
    type: kubernetes.io/dockerconfigjson

