apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{ toYaml .Values.ingress.hosts | indent 4 }}