apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-inference-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: so1s-project-dev

  source:
    repoURL: git@github.com:So1S/deploy.git
    targetRevision: SO1S-349-deploy-alb-nlb-걷어내기
    path: charts/inference

    helm:
      releaseName: inference
      valueFiles:
        - dev-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
