apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-monitoring-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: so1s-project-dev

  source:
    repoURL: https://github.com/So1S/deploy.git
    targetRevision: main
    path: charts/monitoring

    helm:
      releaseName: monitoring
      valueFiles:
        - dev-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
      - CreateNamespace=true
