apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-sealed-secrets
  namespace: argocd
  finalizers: []
spec:
  project: so1s-project-dev

  source:
    repoURL: https://github.com/bitnami-labs/sealed-secrets
    targetRevision: v0.18.1
    path: helm/sealed-secrets
    helm:
      values: |
        tolerations:
          - key: kind
            operator: "Equal"
            value: library
            effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
