apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-istio-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: so1s-project-dev

  source:
    repoURL: https://github.com/so1s/so1s-deploy.git
    targetRevision: main
    path: charts/istio

    helm:
      releaseName: istio
      valueFiles:
        - dev-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
