apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: so1s-backend-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/so1s/api-server
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
spec:
  project: so1s-project-dev

  source:
    repoURL: https://github.com/So1S/deploy.git
    targetRevision: main
    path: charts/backend

    helm:
      releaseName: backend
      valueFiles:
        - dev-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    syncOptions:
      - CreateNamespace=true
