apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    grafana-password: AgB0p4LJ76SMAEF9WsTG4LJLNbVwfN4FDvIrkwjFIZLTSqm5T19JvdBu1mxar4w2wgipvYorgtYGT/bkY02S41XRQn/nrq7ADkULjqDP74oiH7ZAshiA+WUvdpCg1LdAaVEXF1czPO0IxKaTq5Dny0kg5EDTq1G1awfbvTEeOSoZSeKGbr6Zdwd5y2Nlx189xKP2NRyBSogghBRp5D01cYnVNlgYyIvRZh8QI8/unJTtsfP18lJ4J9a2/z31jbJvnK5dPt6P8OkjhiYZK7hcs567YaGhDvnedkHQfVuIuJSTfgBPtmc8jnI/xVFtOKbLhnH99t1C+wvbG9hKu+V69mXl6NwDIn43ly+dP8rw44nsazcgGzs9J7flSg82C2vU5EtRD+qpGiGEA7uD+pdq84dK8AmVr9Xcxb2Jr2Q0uQU5dpHAA1WfkgzipNTpFPeyYPvIcCzDZ/jPIKfBrBoUe23P1cTiVKHvjYIAhSHCZzOGRqVo0kaGy8vH8PHfcKe9NKsTvi0uYNPJzxqENIH0ytBErkHcZLM+i+SH84I0ttMjbNKOsFJH9IcHjL6El4ZQm0T5FzZIHPriSwAcuVfJ2y9NGDrfhpf25OSabMT22b9Fvu4d8QV4q9zHUejRyBZz5QxqlClGhkkO6CmCSJwfaqdBNZTwYi4w7c4Peaq0K66pHb/6mmAOlzgAo3E/BvjDdHSHP+AywPhokSLu
    grafana-user: AgCHspmsuF/Lk07kodXGRtiOvRFtYGeylMdHb4T2oFwFZKYJ4LkYxrFB3Fn7m/RRuxtawiqZfYauL1CtR+VZB5N4D7oLemNzZuyJPOSLsrGpZrNMqKU5vvA+D7Y0hFo6ohsOmqZMmoVr1thlefc4Vd/K7F3ahTJ3915CUSNs24j3zMLMZ0zzgP4dKXPayWFRctqxcj9zP55mJXjSIrKUAzQRV9asqqrJJXUDQH5EAnAUk/RP1Zdzd1SvvCY8DOUBZftminA5oYHw1nipxjHejPI12mAkcV0N5t0AaZshyJKDsE9DzVtQy+7clA9PknqpsG6thystZCWBzrKmA1FBB8LYEeSbgogVjdjvm5LfP9x4evxoGOUa3Bf6k20Q6SmZkCYLX2mESWBlw8ATx2d+kLd6GwhTQ1Zq4fjbTR3vZbS6OYNcmoxmmUx+y9+FA0aJiJvrHPa7BgJhcJko0FmTTu0eeb0JRXAoc9uX9tb4Pc7KyqUXuozlrwfuVuR0+aQPFriECP1o3GYGDv8kUdzT8WubeBUCw3/0x3cjHvtrFNxJnVLBlDlLl5FBfqViDtduNsZLQCSlR/3WMSUBAU8qwlCHv9WeW4JdlgFcdtvq2uokxjtX+U+4SPC+fML4IKGvFF5/pjf+IRfKEIdQ2peyY2knFlmC+tevH/50ehfZlFEfnAxPYZ8e/8hi3R4qzpoT74vIaXePbg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring

