# helm repo add aws https://aws.github.io/eks-charts
# helm install alb -n kube-system -f charts/public/aws-load-balancer-controller/dev-values.yaml aws/aws-load-balancer-controller --create-namespace --wait

clusterName: "prod-so1s"

region: ap-northeast-2

tolerations:
  - key: kind
    operator: "Equal"
    value: "public"
    effect: "NoSchedule"
