apiVersion: v2
name: so1s-backend
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
description: A Helm chart for So1s Backend
type: application
maintainers:
  - name: JihoLee
    email: optional.int@kakao.com
  - name: SungbinIm
    email: dlatqdlatq@naver.com
  - name: ShinilSeop
    email: shinilseop12@gmail.com
sources:
  - https://github.com/So1S/deploy

version: 0.1.0
appVersion: "1.16.0"
kubeVersion: ">=1.22.10-0"