environment: "develop"

fullnameOverride: "sungbin-dev" # 중복된 ClusterRole이 생기면 안되므로 각자 이름을 써놓고 작업해주세요

image:
  repository: "ghcr.io/so1s/poc-nemne"
  tag: "v1"

imagePullSecrets:
  - name: poc-registry

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1

tolerations:
  - key: kind
    operator: "Equal"
    value: "api"
    effect: "NoSchedule"

resourceQuota:
  cpu: "2000m"
  memory: 2Gi

resources:
  limits:
    memory: "300Mi"
    cpu: "300m"
  requests:
    memory: "300Mi"
    cpu: "300m"

ingress:
  annotations:
    kubernetes.io/ingress.class: alb #alb를 사용한다는 의미
    alb.ingress.kubernetes.io/target-type: instance #target이 ec2 인스턴스
    alb.ingress.kubernetes.io/scheme: internet-facing #외부에 노출
    external-dns.alpha.kubernetes.io/hostname: www.so1s.io
  hosts: 
    - www.so1s.io
  paths:
    - /
  tls: []

swagger:
  resources:
    limits:
      memory: "100Mi"
      cpu: "100m"
    requests:
      memory: "300Mi"
      cpu: "300m"
  tolerations:
    - key: kind
      operator: "Equal"
      value: "api"
      effect: "NoSchedule"

pullSecret:
  dockerConfigJson: "Selaed-Secret"