vender: "AWS" # AWS | on-premise

environment: "develop"

fullnameOverride: "so1s-dev"

istioInject:
  enabled: true

image:
  repository: "ghcr.io/so1s/api-server"
  tag: "latest"

imagePullSecrets: []

imagePullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1

tolerations:
  - key: kind
    operator: "Equal"
    value: "application"
    effect: "NoSchedule"

resourceQuota:
  cpu: "2000m"
  memory: 2500Mi

resources:
  limits:
    memory: "450Mi"
    cpu: "300m"
  requests:
    memory: "450Mi"
    cpu: "300m"

ingress:
  annotations: {}
  hosts:
    - test-backend.so1s.io
  paths:
    - /
  tls: []

serviceMonitor:
  enabled: true
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  namespace: backend
  interval: 30s
  telemetryPath: /actuator/prometheus
  labels:
    release: monitoring
  timeout: 10s

preInstall:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "application"
      effect: "NoSchedule"
