vender: "AWS" # AWS | on-premise

environment: "develop"

fullnameOverride: "so1s-dev" # 중복된 ClusterRole이 생기면 안되므로 각자 이름을 써놓고 작업해주세요

image:
  repository: "ghcr.io/so1s/api-server"
  tag: "latest"

imagePullSecrets:
  - name: so1s

imagePullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1

tolerations:
  - key: kind
    operator: "Equal"
    value: "api"
    effect: "NoSchedule"

resourceQuota:
  cpu: "2000m"
  memory: 2500Mi

resources:
  limits:
    memory: "450Mi"
    cpu: "300m"
  requests:
    memory: "450Mi"
    cpu: "300m"

ingress:
  annotations:
    kubernetes.io/ingress.class: alb #alb를 사용한다는 의미
    alb.ingress.kubernetes.io/target-type: instance #target이 ec2 인스턴스
    alb.ingress.kubernetes.io/scheme: internet-facing #외부에 노출
    external-dns.alpha.kubernetes.io/hostname: test.www.so1s.io
  hosts: 
    - test.www.so1s.io
  paths:
    - /
  tls: []

swagger:
  image:
    repository: swaggerapi/swagger-ui
    tag: v4.13.2

  imagePullSecrets:
    - name: so1s

  imagePullPolicy: Always

  resources:
    limits:
      memory: "50Mi"
      cpu: "25m"
    requests:
      memory: "50Mi"
      cpu: "25m"


  tolerations:
    - key: kind
      operator: "Equal"
      value: "api"
      effect: "NoSchedule"


  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      external-dns.alpha.kubernetes.io/hostname: test.swagger.so1s.io
    hosts: 
      - test.swagger.so1s.io
    paths:
      - /
    tls: []
  
  service:
    port: 80
    targetPort: 8080