vender: "AWS" # AWS | on-premise

environment: "develop"

fullnameOverride: "so1s-prod"

istioInject:
  enabled: true

image:
  repository: "ghcr.io/so1s/api-server"
  tag: "1.3.1"

imagePullSecrets:
  - name: so1s

imagePullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

tolerations:
  - key: kind
    operator: "Equal"
    value: "application"
    effect: "NoSchedule"

resourceQuota:
  cpu: "4000m"
  memory: 5Gi

resources:
  limits:
    memory: "900Mi"
    cpu: "600m"
  requests:
    memory: "900Mi"
    cpu: "600m"

ingress:
  annotations: {}
  hosts:
    - backend.so1s.io
  paths:
    - /
  tls: []

serviceMonitor:
  enabled: true
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  namespace: backend
  interval: 30s
  telemetryPath: /actuator/prometheus
  labels:
    release: monitoring
  timeout: 10s

swagger:
  istioInject:
    enabled: true

  resources:
    limits:
      memory: "100Mi"
      cpu: "50m"
    requests:
      memory: "50Mi"
      cpu: "30m"
  tolerations:
    - key: kind
      operator: "Equal"
      value: "application"
      effect: "NoSchedule"

  ingress:
    enabled: false
    annotations: {}
    hosts:
      - swagger.so1s.io
    paths:
      - /
    tls: []

preInstall:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "application"
      effect: "NoSchedule"
