environment: "production"

replicaCount: 2

image:
  repository:
  tag:

imagePullSecrets: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

resourceQuota:
  cpu: "4000m"
  memory: "4Gi"

resources:
  limits:
    memory: "1000Mi"
    cpu: "1000m"
  requests:
    memory: "1000Mi"
    cpu: "1000m"