
vender: "AWS" # AWS | on-premise

environment: "develop" # develop | production

namespaceOverride: ""

replicaCount: 1

hostname: ""

image:
  repository: nginx
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

imagePullPolicy: Always

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: true
  annotations: {}
  labels: {}
  hosts: []
  paths: []
  tls: []
  pathType: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  limits:
    memory: "1000Mi"
    cpu: "1000m"
  requests:
    memory: "1000Mi"
    cpu: "1000m"

resourceQuota:
  cpu: "3000m"
  memory: "3000Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations:
  - key: kind
    operator: "Equal"
    value: "api"
    effect: "NoSchedule"

affinity: {}
