apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  {{- with .Values.affinity }}
  nodeAffinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  storageClassName: local-storage
  local:
    path: /var/local/data/so1s/database