apiVersion: v1
kind: Service
metadata:
  name: so1s-database
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
