# helm install argocd -n argocd -f argocd/dev-values.yaml argo/argo-cd --create-namespace --wait

server:
  logFormat: json

  extraArgs: # To avoid internal redirection loops from HTTP to HTTPS
    - --insecure
  tolerations:
    - key: kind
      operator: "Equal"
      value: "library"
      effect: "NoSchedule"
  ingress:
    enabled: false
    annotations: {}
    hosts: []
    tls: []
  service:
    type: ClusterIP
    annotations: {}

controller:
  logFormat: json

  tolerations:
    - key: kind
      operator: "Equal"
      value: "library"
      effect: "NoSchedule"

dex:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "library"
      effect: "NoSchedule"

redis:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "library"
      effect: "NoSchedule"

repoServer:
  logFormat: json

  tolerations:
    - key: kind
      operator: "Equal"
      value: "library"
      effect: "NoSchedule"

applicationSet:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "library"
      effect: "NoSchedule"

notification:
  tolerations:
    - key: kind
      operator: "Equal"
      value: "library"
      effect: "NoSchedule"

notifications:
  logFormat: json

  tolerations:
    - key: kind
      operator: "Equal"
      value: "library"
      effect: "NoSchedule"
