apiVersion: v1
data:
  .dockerconfigjson: "Selead-Secret"
kind: Secret
metadata:
  creationTimestamp: "2022-07-25T07:33:55Z"
  name: poc-registry
  namespace: backend
  resourceVersion: "4570381"
  uid: dade6e85-b245-4bd3-8d2f-be5b0d9db3cb
type: kubernetes.io/dockerconfigjson
