name: CI
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.8.2
      - name: Helm Deps
        run: |
          for dir in $(ls -d charts/*); do
            FILE="Chart.yaml"
 
            if [ -e $dir/$FILE ];then
              helm dependency update $dir;
              helm dependency list $dir;
            fi
          done
      - name: lint chart
        run: |
          for dir in $(ls -d charts/*); do
            FILE="Chart.yaml"
            NAME= $dir | sed 's/charts\///g'
            if [ -e $dir/$FILE ];then
              helm lint $dir \
              && helm template backend -n backend -f ./charts/backend/dev-values.yaml ./charts/backend  --create-namespace --wait > dev-backend.yaml \
              && helm template backend -n backend -f ./charts/backend/prod-values.yaml ./charts/backend  --create-namespace --wait > prod-backend.yaml
            fi
          done